export const DASHBOARD_PANE_MIN_WIDTH = 460;
export const SIDEBAR_WIDTH = 80;
export const SUPPORTED_METHODS = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'];
export const TOOLTIP_DELAY = 0.05;
export const KUSK_SETTINGS_TARGET_API = 'KUSK_SETTINGS_TARGET_API';
export const KUSK_SETTINGS_TARGET_DEV_PORTAL = 'KUSK_SETTINGS_TARGET_DEV_PORTAL';
export const KUSK_USER_ANALYTICS_OFF = 'KUSK_USER_ANALYTICS_OFF';
export const APP_ROUTES = ['/settings', '/staticroute'];
export const KUSK_DOCS = 'https://docs.kusk.io/';
