apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: staticroute-sample
spec:
  # Envoy Fleet (its name and namespace) to deploy the configuration to, here - deployed EnvoyFleet with the name "default" in the namespace "default".
  # Optional, if not specified - single (default) fleet autodetection will be performed in the cluster.
  fleet:
    name: default
    namespace: default
  hosts: [<string>, <string>, ...]
  paths:
    # Consists of path matchers with HTTP methods (lowercase), which in turn either:
    # 1. "route" (proxying) to the upstream host or
    # 2. "redirect" to other endpoint
    <path_match>:
      <http_method>:
        # "route" defines proxying parameters. Mutually exlusive with "redirect".
        route:
          # upstream is the container for the upstream host specification.
          upstream:
            # host defines the hostname to proxy to. Mutually exlusive with service.
            host:
              # DNS name to proxy to
              hostname: <string>
              # Port to proxy to
              port: <int>
            # service is the convenient way to configure proxying to Kubernetes services. Mutually exlusive with the "host".
            service:
              # service name
              name: <string>
              namespace: <string>
              port: 8080
            # rewrites path with the regex and substitution patterns.
            rewrite:
              pattern: <string> # path regex pattern
              substitution: <string> # path substitution pattern.
          # Optional
          qos:
            # the timeout for the upstream connection, seconds. 0 means forever, if unspecified - 15 seconds.
            request_timeout: <int>
            # the timeout for the idle upstream of downstream connection, seconds. 0 means forever, unspecified default 1h.
            idle_timeout: <int>
            # retres define how many retries to upstream with failed (50x code) requests, number. Default 1.
            retries: <int>
          # Optional
          cors:
            # allowed origins returned in Access-Control-Allow-Origin header
            # the list of domain names
            # Note - regexs other than the wildcard ("*") are not supported right now.
            origins:
              - '*'
            # allowed methods to call this endpoint returned in Access-Control-Allow-Methods header
            # the list of methods
            methods:
              - POST
              - GET
            # allowed headers returned in Access-Control-Allow-Headers header
            # the list of headers
            headers:
              - Content-Type
            # allow browser to send credentials, returned with Access-Control-Allow-Credentials header
            credentials: <true|false>
            # allowed headers that browser can access returned with  Access-Control-Expose-Headers header
            # the list of headers
            expose_headers:
              - X-Custom-Header1
              - X-Custom-Header2
            # how long to cache this CORS information for the browser, returned with Access-Control-Max-Age.
            max_age: <int>
          # Enable establishing Websockets connections
          websocket: <true|false>
        # "redirect" creates HTTP redirect to other endpoint. Mutually exclusive with "route".
        redirect:
          # redirect to http or https
          scheme_redirect: <http|https>
          # redirect to this hostname
          host_redirect: <string>
          # redirects to different port
          port_redirect: <int>
          # redirect to different URL path. Mutually exlusive with rewrite_regex.
          path_redirect: '<string>'
          # redirect using the rewrite rule. Mutually exlusive with path_redirect.
          rewrite_regex:
            # regex
            pattern: <string>
            # regex parameters substitution pattern
            substitution: <string>
          # response code, by default - Permanent Redirect HTTP 308
          # available HTTP codes: 301, 302, 303, 307, 308
          response_code: <int>
