export const enum Events {
  PUBLISH_API_MODAL_LOADED = 'PUBLISH_API_MODAL_LOADED',
  PUBLISH_API_MODAL_DISMISSED = 'PUBLISH_API_MODAL_DISMISSED',
  PUBLISH_API_MODAL_OPENED = 'PUBLISH_API_MODAL_OPENED',
  PUBLISH_API_SUBMITTED = 'PUBLISH_API_SUBMITTED',
  API_PAGE = 'API_PAGE',
  API_LIST_LOADED = 'API_LIST_LOADED',
  API_INFO_LOADED = 'API_INFO_LOADED',
  API_INFO_CLOSED = 'API_INFO_CLOSED',
  API_CRD_LOADED = 'API_CRD_LOADED',
  API_DEFINITION_LOADED = 'API_DEFINITION_LOADED',
  API_PUBLIC_DEFINITION_LOADED = 'API_PUBLIC_DEFINITION_LOADED',
  API_KUSK_EXTENSION_LOADED = 'API_KUSK_EXTENSION_LOADED',
  API_MENU_CLICKED = 'API_MENU_CLICKED',
  ENVOY_FLEET_PAGE = 'ENVOY_FLEET_PAGE',
  ENVOY_FLEET_LIST_LOADED = 'ENVOY_FLEET_LIST_LOADED',
  ENVOY_FLEET_INFO_LOADED = 'ENVOY_FLEET_INFO_LOADED',
  ENVOY_FLEET_INFO_CLOSED = 'ENVOY_FLEET_INFO_CLOSED',
  ENVOY_FLEET_CRD_LOADED = 'ENVOY_FLEET_CRD_LOADED',
  ENVOY_FLEET_API_LOADED = 'ENVOY_FLEET_API_LOADED',
  ENVOY_FLEET_STATIC_ROUTES_LOADED = 'ENVOY_FLEET_STATIC_ROUTES_LOADED',
  ENVOY_FLEET_MENU_CLICKED = 'ENVOY_FLEET_MENU_CLICKED',
  PUBLISH_ENVOY_FLEET_MODAL_LOADED = 'PUBLISH_ENVOY_FLEET_MODAL_LOADED',
  PUBLISH_ENVOY_FLEET_MODAL_DISMISSED = 'PUBLISH_ENVOY_FLEET_MODAL_DISMISSED',
  PUBLISH_ENVOY_FLEET_MODAL_OPENED = 'PUBLISH_ENVOY_FLEET_MODAL_OPENED',
  PUBLISH_ENVOY_FLEET_SUBMITTED = 'PUBLISH_ENVOY_FLEET_SUBMITTED',
  STATIC_ROUTES_PAGE = 'STATIC_ROUTES_PAGE',
  STATIC_ROUTES_LIST_LOADED = 'STATIC_ROUTES_LIST_LOADED',
  STATIC_ROUTES_INFO_LOADED = 'STATIC_ROUTES_INFO_LOADED',
  STATIC_ROUTES_INFO_CLOSED = 'STATIC_ROUTES_INFO_CLOSED',
  STATIC_ROUTES_CRD_LOADED = 'STATIC_ROUTES_CRD_LOADED',
  STATIC_ROUTES_MENU_CLICKED = 'STATIC_ROUTES_MENU_CLICKED',

  PUBLISH_STATIC_ROUTES_MODAL_LOADED = 'PUBLISH_STATIC_ROUTES_MODAL_LOADED',
  PUBLISH_STATIC_ROUTES_MODAL_DISMISSED = 'PUBLISH_STATIC_ROUTES_MODAL_DISMISSED',
  PUBLISH_STATIC_ROUTES_MODAL_OPENED = 'PUBLISH_STATIC_ROUTES_MODAL_OPENED',
  PUBLISH_STATIC_ROUTES_SUBMITTED = 'PUBLISH_STATIC_ROUTES_SUBMITTED',
  SETTINGS_PAGE = 'SETTINGS_PAGE',
  ADD_SERVER_MODAL_LOADED = 'ADD_SERVER_MODAL_LOADED',
  ADD_SERVER_MODAL_DISMISSED = 'ADD_SERVER_MODAL_DISMISSED',
  SERVER_CHANGED = 'SERVER_CHANGED',
  DROPDOWN_SELECTED = 'DROPDOWN_SELECTED',
}

export const enum ANALYTIC_TYPE {
  PAGE,
  ACTION,
}

export interface AnalyticEvent {
  type: ANALYTIC_TYPE;
  eventName: string;
  page?: string;
}
