name: build

concurrency:
  group: build
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          build-args: |
            SEGMENT_API_KEY=${{ secrets.REACT_APP_SEGMENT_API_KEY }}
