name: build

concurrency:
  group: build
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths-ignore: [Dockerfile]
  pull_request:
    branches: [main]
    paths-ignore: [Dockerfile]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci --prefer-offline
      - run: npm run build
