name: Release Kusk Gateway Dashboard

concurrency:
  group: "release"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  release:
    name: Create and upload release-artifacts
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker Metadata for Kusk Gateway Dashboard
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/kusk-gateway-dashboard
          tags: |
            type=match,pattern=v(.*)
            type=sha
          flavor: |
            latest=true
      
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
